"""Postgres backend for the store — a thin psycopg proxy that lets the existing
SQLite-flavoured SQL in ``store.py`` run unchanged against Supabase/Postgres.

The whole codebase talks to the database through the connection object returned
by ``store.open_store``: it calls ``conn.execute(sql, params)``, iterates the
result, wraps writes in ``with conn:`` and eventually ``conn.close()``. sqlite3
and psycopg both offer that surface, but with three incompatibilities this
module papers over so ``store.py`` needs no edits:

1. **Placeholders.** sqlite3 uses ``?`` (positional) and ``:name`` (named);
   psycopg uses ``%s`` and ``%(name)s``. ``_translate`` rewrites them.
2. **``with conn:`` semantics.** For sqlite3 it's *transaction only* (commit on
   success / rollback on error, connection stays open) and is used many times
   per connection. psycopg's own context manager *closes* the connection on
   exit, which would break the second ``with``. So the proxy implements the
   sqlite3 semantics explicitly.
3. **Row access.** ``store.py`` mixes mapping access (``row["col"]``,
   ``dict(row)``) with positional access (``fetchone()[0]``). ``_hybrid_row``
   returns rows that support both, like ``sqlite3.Row``.
"""

from __future__ import annotations

import os
import re

# psycopg is only needed when hosting on Postgres; keep it an optional import so
# the core package (local SQLite) has no hard dependency on it.
try:  # pragma: no cover - import guard
    import psycopg
except ModuleNotFoundError:  # pragma: no cover
    psycopg = None  # type: ignore[assignment]


# --- SQL dialect: Postgres mirror of store._SCHEMA -------------------------
# Same tables/columns/indexes as the SQLite schema, translated to Postgres:
#   INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED ... AS IDENTITY
#   REAL                              -> DOUBLE PRECISION
#   (no PRAGMA / WAL — those are SQLite-only)
# The enrich columns are included directly here, so there's no separate ALTER
# migration step on Postgres (the SQLite path keeps its additive _migrate()).
_PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS posts (
    uri           TEXT PRIMARY KEY,
    cid           TEXT,
    source        TEXT NOT NULL,
    url           TEXT,
    text          TEXT,
    created_at    TEXT,
    indexed_at    TEXT,
    author_did    TEXT,
    author_handle TEXT,
    author_name   TEXT,
    likes         INTEGER DEFAULT 0,
    reposts       INTEGER DEFAULT 0,
    replies       INTEGER DEFAULT 0,
    quotes        INTEGER DEFAULT 0,
    raw           TEXT,
    fetched_at    TEXT NOT NULL,
    sentiment_score  DOUBLE PRECISION,
    sentiment_label  TEXT,
    assets           TEXT,
    catalyst         TEXT,
    sentiment_model  TEXT,
    enriched_at      TEXT,
    event            TEXT,
    severity         TEXT
);
-- Additive migration for a pre-existing posts table (the CREATE above is a
-- no-op once it exists, and Postgres has no separate _migrate step)
ALTER TABLE posts ADD COLUMN IF NOT EXISTS event    TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS severity TEXT;
CREATE INDEX IF NOT EXISTS idx_posts_indexed_at ON posts(indexed_at);
CREATE INDEX IF NOT EXISTS idx_posts_source     ON posts(source);

CREATE TABLE IF NOT EXISTS actions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset       TEXT NOT NULL,
    action      TEXT NOT NULL,
    direction   TEXT,
    confidence  DOUBLE PRECISION,
    horizon     TEXT,
    score       DOUBLE PRECISION,
    catalysts   TEXT,
    rationale   TEXT,
    freshness_minutes DOUBLE PRECISION,
    created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_actions_created_at ON actions(created_at);

CREATE TABLE IF NOT EXISTS bias_snapshots (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts        TEXT NOT NULL,
    layer     TEXT NOT NULL,
    asset     TEXT,
    bias      DOUBLE PRECISION,
    label     TEXT,
    evidence  DOUBLE PRECISION
);
CREATE INDEX IF NOT EXISTS idx_bias_snap ON bias_snapshots(layer, asset, ts);

CREATE TABLE IF NOT EXISTS alerts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset        TEXT NOT NULL,
    action       TEXT NOT NULL,
    confidence   DOUBLE PRECISION,
    horizon      TEXT,
    sinks        TEXT,
    delivered_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alerts_delivered ON alerts(delivered_at);

CREATE TABLE IF NOT EXISTS monitor_fires (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monitor   TEXT NOT NULL,
    kind      TEXT NOT NULL,
    ref       TEXT NOT NULL,
    fired_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_monitor_fires ON monitor_fires(monitor, kind, fired_at);

CREATE TABLE IF NOT EXISTS cycle_health (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle       INTEGER,
    started_at  TEXT NOT NULL,
    duration_ms DOUBLE PRECISION,
    fetched     INTEGER,
    inserted    INTEGER,
    enriched    INTEGER,
    llm_calls   INTEGER,
    actions     INTEGER,
    notable     INTEGER,
    error       TEXT,
    per_source  TEXT,
    summary     TEXT
);
CREATE INDEX IF NOT EXISTS idx_cycle_health ON cycle_health(started_at);

CREATE TABLE IF NOT EXISTS score_snapshots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle       INTEGER,
    ts          TEXT NOT NULL,
    asset       TEXT NOT NULL,
    sentiment   DOUBLE PRECISION,
    strength    DOUBLE PRECISION,
    score       DOUBLE PRECISION,
    direction   TEXT,
    mentions    INTEGER,
    velocity    DOUBLE PRECISION,
    catalysts   TEXT,
    sources     TEXT,
    latest_at   TEXT,
    action      TEXT,
    confidence  DOUBLE PRECISION,
    horizon     TEXT,
    layers      TEXT,
    price_at_score DOUBLE PRECISION,
    created_at  TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_score_snap_ts_asset ON score_snapshots(ts, asset);
CREATE INDEX IF NOT EXISTS idx_score_snap_asset ON score_snapshots(asset, ts);

CREATE TABLE IF NOT EXISTS score_outcomes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id   BIGINT NOT NULL,
    asset         TEXT NOT NULL,
    scored_at     TEXT NOT NULL,
    horizon_hours DOUBLE PRECISION NOT NULL,
    due_at        TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'pending',
    attempts      INTEGER DEFAULT 0,
    resolved_at   TEXT,
    entry_px      DOUBLE PRECISION,
    exit_px       DOUBLE PRECISION,
    ret           DOUBLE PRECISION,
    btc_ret       DOUBLE PRECISION
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_outcome_snap_h ON score_outcomes(snapshot_id, horizon_hours);
CREATE INDEX IF NOT EXISTS idx_outcome_due ON score_outcomes(status, due_at);

CREATE TABLE IF NOT EXISTS market_moves (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset        TEXT NOT NULL,
    detected_at  TEXT NOT NULL,
    window_hours DOUBLE PRECISION NOT NULL,
    start_px     DOUBLE PRECISION,
    end_px       DOUBLE PRECISION,
    ret          DOUBLE PRECISION NOT NULL,
    catalysts    TEXT,
    evidence     TEXT,
    signal_score DOUBLE PRECISION,
    action       TEXT,
    explained    INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_moves_asset ON market_moves(asset, detected_at);
"""

# ``:name`` not preceded by another ``:`` (so Postgres ``::type`` casts, should
# any appear, are left alone), followed by an identifier.
_NAMED_PARAM = re.compile(r"(?<!:):([a-zA-Z_]\w*)")


def _translate(sql: str) -> str:
    """Rewrite sqlite3 placeholders to psycopg style.

    ``:name`` -> ``%(name)s`` and ``?`` -> ``%s``. The store's SQL never mixes
    the two styles in one statement and has no ``%`` literals or ``?`` inside
    string literals, so these two substitutions are safe.
    """
    sql = _NAMED_PARAM.sub(r"%(\1)s", sql)
    sql = sql.replace("?", "%s")
    return sql


def _hybrid_row(cursor):
    """psycopg row factory yielding rows usable by key *and* by position.

    ``dict(row)`` and ``row["col"]`` work (mapping), and ``row[0]`` works
    (position) — matching ``sqlite3.Row`` so ``store.py`` needs no changes.
    """
    cols = [d.name for d in cursor.description] if cursor.description else []

    def make(values):
        return _Row(cols, values)

    return make


class _Row(dict):
    """dict row that also supports integer indexing."""

    __slots__ = ("_values",)

    def __init__(self, cols, values):
        super().__init__(zip(cols, values))
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


class PgConnection:
    """A sqlite3.Connection-shaped facade over a psycopg connection."""

    def __init__(self, conn):
        self._conn = conn

    # -- statement execution (mirrors sqlite3.Connection.execute) -----------
    def execute(self, sql: str, params=()):
        cur = self._conn.cursor()
        cur.execute(_translate(sql), params or None)
        return cur

    def executemany(self, sql: str, seq_of_params):
        cur = self._conn.cursor()
        cur.executemany(_translate(sql), list(seq_of_params))
        return cur

    def executescript(self, script: str):
        # psycopg's extended protocol allows one statement per execute, so run
        # the schema statement-by-statement. Safe here: no ';' inside literals.
        for stmt in script.split(";"):
            if stmt.strip():
                self._conn.execute(stmt)
        return self

    # -- transaction control (sqlite3 semantics: no close on __exit__) -------
    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is not None:
            self._conn.rollback()
        else:
            self._conn.commit()
        return False  # don't suppress exceptions

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    @property
    def raw(self):
        """The underlying psycopg connection (for pandas / COPY, if needed)."""
        return self._conn


def open_pg(url: str) -> PgConnection:
    """Connect to Postgres, ensure the schema exists, return the proxy.

    ``url`` is a standard ``postgresql://…`` DSN (the Supabase connection
    string). autocommit is off so ``with conn:`` blocks are real transactions,
    exactly like the SQLite path.
    """
    if psycopg is None:  # pragma: no cover
        raise RuntimeError(
            "DATABASE_URL is set but psycopg is not installed — "
            "install the hosting extra: pip install 'catalyst[pg]'"
        )
    # Optional out-of-band password: when DATABASE_PASSWORD is set it's passed to
    # libpq as a separate parameter, so the DSN needs no password and special
    # characters (@ : / # etc.) require NO percent-encoding. This is the robust
    # way to feed a Supabase DB password that contains symbols.
    extra: dict[str, object] = {}
    pw = os.environ.get("DATABASE_PASSWORD")
    if pw:
        extra["password"] = pw

    # prepare_threshold=None disables psycopg's automatic prepared statements,
    # which otherwise break under Supabase's transaction-mode pooler (pgbouncer
    # on port 6543). Harmless on the session pooler / direct connection, so this
    # makes any Supabase connection string work.
    conn = psycopg.connect(
        url, autocommit=False, row_factory=_hybrid_row, prepare_threshold=None, **extra
    )
    proxy = PgConnection(conn)
    proxy.executescript(_PG_SCHEMA)
    conn.commit()
    return proxy


def database_url() -> str | None:
    """The configured Postgres DSN, if any. Presence of this selects the backend."""
    return os.environ.get("DATABASE_URL") or None
